import { ContentType, ContentItem } from './types';

export const MOCK_DATA: ContentItem[] = [
  {
    id: '1',
    type: ContentType.ARTICLE,
    title: 'The Future of Generative AI in Enterprise Workflows',
    summary: 'Exploring how LLMs are reshaping internal tools and productivity suites across the industry.',
    content: 'Generative AI is not just a buzzword; it is fundamentally changing how we approach software development and internal operations. From automated code reviews to intelligent knowledge bases, the integration of models like Gemini 2.5 Flash is accelerating our velocity...',
    thumbnail: 'https://picsum.photos/800/400?random=1',
    author: { name: 'Sarah Chen', role: 'CTO', avatar: 'https://picsum.photos/100/100?random=10' },
    date: '2023-10-24',
    tags: ['AI', 'Productivity', 'Strategy'],
    likes: 124,
    comments: [],
  },
  {
    id: '2',
    type: ContentType.VIDEO,
    title: 'Q3 All-Hands Meeting Recording',
    summary: 'Full recording of the quarterly meeting covering financial results and Q4 roadmap.',
    thumbnail: 'https://picsum.photos/800/400?random=2',
    author: { name: 'Comms Team', role: 'Internal', avatar: 'https://picsum.photos/100/100?random=11' },
    date: '2023-10-20',
    tags: ['Company', 'All-Hands'],
    likes: 89,
    comments: [],
    mediaUrl: '#',
    duration: '45:30',
  },
  {
    id: '3',
    type: ContentType.PODCAST,
    title: 'Tech Talk Ep. 42: Micro-Frontends',
    summary: 'Deep dive into our migration strategy to micro-frontends with the Frontend Platform team.',
    thumbnail: 'https://picsum.photos/800/400?random=3',
    author: { name: 'Dave Miller', role: 'Staff Engineer', avatar: 'https://picsum.photos/100/100?random=12' },
    date: '2023-10-18',
    tags: ['Engineering', 'Architecture', 'Audio'],
    likes: 56,
    comments: [],
    mediaUrl: '#',
    duration: '22:15',
  },
  {
    id: '4',
    type: ContentType.EVENT,
    title: 'AI Hackathon 2024 Kickoff',
    summary: 'Join us for a 48-hour sprint to build the next generation of internal tools using GenAI.',
    thumbnail: 'https://picsum.photos/800/400?random=4',
    author: { name: 'Innovation Lab', role: 'R&D', avatar: 'https://picsum.photos/100/100?random=13' },
    date: '2023-11-01',
    tags: ['Hackathon', 'Fun', 'Coding'],
    likes: 204,
    comments: [],
    location: 'Main Auditorium & Zoom',
  },
  {
    id: '5',
    type: ContentType.ARTICLE,
    title: 'New Security Protocols for Cloud Access',
    summary: 'Important updates regarding zero-trust architecture implementation starting next month.',
    content: 'Security is paramount. We are rolling out new zero-trust access policies for all production environments. Please review the updated documentation regarding VPN usage and 2FA requirements...',
    thumbnail: 'https://picsum.photos/800/400?random=5',
    author: { name: 'Alex Rivera', role: 'CISO', avatar: 'https://picsum.photos/100/100?random=14' },
    date: '2023-10-23',
    tags: ['Security', 'Infrastructure', 'Important'],
    likes: 45,
    comments: [],
  },
];
